### ISSUE TITLE
Problème de cache ?

### ISSUE THREAD

**Issue by martintamare** [ovh-ux/ovh-manager-telecom#630]
### Description

Quand on change le numéro d'une ligne / pack ADSL, ou un numéro de téléphone, alors c'est pris en compte niveau API, mais l'affichage marche pas.
Peux être prévoir un bouton reset cache ?

**Comment by Jisay** [comment]
Merci pour la remontée, on s'occupe de remonter à l'équipe concernée.

**Comment by Jisay** [comment]
Celà devrait être mieux maintenant. Il reste encore un léger lag (de qques sec max). 
Peux-tu me confirmer @martintamare ?

**Comment by martintamare** [comment]
Ca a l'air mieux effectivement !
Merci pour la réactivité :)
